### Sign up

POST http://localhost:3000/users
Content-Type: application/json

{
    "email" : "test1243@test.com",
    "password": "123ABCaaa!"
}

### Sign in

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "test1243@test.com",
    "password": "123ABCaaa!"
}

### Me

GET http://localhost:3000/users/me
Content-Type: application/json
x-access-token: 79ea15c5d0c8c362a29db1fa7cdf6221b74c90e562ec95f673

### Update user profile

PUT http://localhost:3000/users/1
Content-Type: application/json
x-access-token: 79ea15c5d0c8c362a29db1fa7cdf6221b74c90e562ec95f673

{
    "email": "test1243@test.com",
    "bio": "Lorem ipsum dolor sit amet",
    "fullName": "Test Bela"
}

### Update password

PUT http://localhost:3000/users/1/password
Content-Type: application/json
x-access-token: 79ea15c5d0c8c362a29db1fa7cdf6221b74c90e562ec95f673

{
    "password": "123ABCaaa!!!"
}

### Add role
PUT http://localhost:3000/users/1/role
Content-Type: application/json
x-access-token: 79ea15c5d0c8c362a29db1fa7cdf6221b74c90e562ec95f673

{
    "role": "SUPERVISOR"
}

### Delete user
DELETE  http://localhost:3000/users/1
Content-Type: application/json
x-access-token: 79ea15c5d0c8c362a29db1fa7cdf6221b74c90e562ec95f673
