### Sign up

POST http://localhost:3000/users
Content-Type: application/json

{
    "email" : "test1243@test.com",
    "password": "123ABCaaa!"
}

### Sign in

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email" : "test1243@test.com",
    "password": "123ABCaaa!"
}

### Me

GET http://localhost:3000/users/me
Content-Type: application/json
x-access-token: a45a69058db351c511fe7a96535b4acddee5bb4c5a9f15853d

### Update user profile

PUT http://localhost:3000/users/9
Content-Type: application/json
x-access-token: a45a69058db351c511fe7a96535b4acddee5bb4c5a9f15853d

{
    "email": "test1243@test.com",
    "bio": "Lorem ipsum dolor sit amet",
    "fullName": "Test Bela"
}

### Update password

PUT http://localhost:3000/users/9/password
Content-Type: application/json
x-access-token: a45a69058db351c511fe7a96535b4acddee5bb4c5a9f15853d

{
    "password": "123ABCaaa!!!"
}

### Add role
PUT http://localhost:3000/users/9/role
Content-Type: application/json
x-access-token: a45a69058db351c511fe7a96535b4acddee5bb4c5a9f15853d

{
    "role": "SUPERVISOR"
}

### Add role
DELETE  http://localhost:3000/users/5
Content-Type: application/json
x-access-token: a45a69058db351c511fe7a96535b4acddee5bb4c5a9f15853d
